#!/usr/bin/env npx tsx
/**
 * Update Telegram Feed Data
 *
 * This script fetches the latest posts from configured Telegram channels
 * and updates the data/telegram-feed.ts file.
 *
 * Usage:
 *   npx tsx scripts/update-telegram-feed.ts
 *
 * Note: Requires the telegram-mcp MCP server to be running.
 * Run this locally before deploying to update content.
 */

import { writeFileSync } from 'fs'
import { join } from 'path'

// Configuration
const CHANNELS_TO_FETCH = [
  { id: 'tigerrising', username: 'tigerrising', name: '이순신김여정🌹', limit: 20 },
  // Add more channels here as needed
]

const OUTPUT_FILE = join(__dirname, '../data/telegram-feed.ts')

interface TelegramMessage {
  id: number
  author: string
  date: string
  message: string
}

function extractHashtags(message: string): string[] {
  const regex = /#[\w]+/g
  return message.match(regex) || []
}

function hasKoreanText(text: string): boolean {
  // Korean Unicode ranges: Hangul Syllables (AC00-D7AF), Hangul Jamo (1100-11FF)
  const koreanRegex = /[\uAC00-\uD7AF\u1100-\u11FF]/
  return koreanRegex.test(text)
}

function generateTypeScriptFile(posts: any[], channels: any[]): string {
  const channelsJson = JSON.stringify(channels, null, 2)
  const postsJson = posts.map(post => ({
    id: post.id,
    channelId: post.channelId,
    channelName: post.channelName,
    channelUsername: post.channelUsername,
    author: post.author,
    date: post.date,
    message: post.message,
    hashtags: post.hashtags,
    hasKorean: post.hasKorean,
  }))

  return `// Auto-generated by scripts/update-telegram-feed.ts
// Last updated: ${new Date().toISOString()}

export interface TelegramPost {
  id: number
  channelId: string
  channelName: string
  channelUsername: string
  author?: string
  date: string
  message: string
  hashtags: string[]
  hasKorean: boolean
}

export interface TelegramChannel {
  id: string
  name: string
  username: string
  description: string
  avatar?: string
  category: 'owned' | 'trusted' | 'news'
}

export const telegramChannels: TelegramChannel[] = ${channelsJson}

export const telegramFeed: TelegramPost[] = ${JSON.stringify(postsJson, null, 2)}

// Get posts by channel
export function getPostsByChannel(channelId: string): TelegramPost[] {
  return telegramFeed.filter(post => post.channelId === channelId)
}

// Get latest posts across all channels
export function getLatestPosts(limit: number = 10): TelegramPost[] {
  return [...telegramFeed]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, limit)
}

// Get channel by id
export function getChannel(channelId: string): TelegramChannel | undefined {
  return telegramChannels.find(ch => ch.id === channelId)
}
`
}

async function main() {
  console.log('\n📱 Telegram Feed Updater')
  console.log('========================\n')

  console.log('Note: This script requires manual data extraction from Telegram MCP.')
  console.log('To update the feed:')
  console.log('')
  console.log('1. Use Claude Code with the telegram-mcp to fetch messages:')
  console.log('   mcp__telegram-mcp__get_messages({ chat_id: "tigerrising", page_size: 20 })')
  console.log('')
  console.log('2. Update data/telegram-feed.ts with the new content')
  console.log('')
  console.log('For automated updates, consider setting up a cron job that:')
  console.log('- Runs this script locally')
  console.log('- Commits and pushes the updated data file')
  console.log('- Triggers a Vercel deploy')
  console.log('')
  console.log('Current channels configured:')
  CHANNELS_TO_FETCH.forEach(ch => {
    console.log(`  - @${ch.username} (${ch.name})`)
  })
  console.log('')
}

main().catch(console.error)
